
name: 'terminology'
version: '1.0.0'
config-version: 2

profile: 'default'

seed-paths: ["terminology"]
macro-paths: ["macros"]

vars:
  terminology_database: tuva
  terminology_schema: terminology_forrest_test
